# =========================================================================
# 1. CONFIGURATION DE L'APPLICATION
# =========================================================================
spring.application.name=hopital

# =========================================================================
# 2. CONFIGURATION DE LA BASE DE DONNEES (PostgreSQL)
# =========================================================================
# Remplacez "localhost:5432/ma_base_de_donnees" par vos informations
spring.datasource.url=jdbc:postgresql://localhost:5432/sig_hopital
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Optimisation du pool de connexions (HikariCP, par défaut dans Spring Boot)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000

# =========================================================================
# 3. CONFIGURATION DE SPRING DATA JPA / HIBERNATE
# =========================================================================
spring.jpa.hibernate.ddl-auto=update

# Activation de la vision sur le generated SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Specifie usage de Postresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================================================================
# 4. CONFIGURATION DE THYMELEAF
# =========================================================================
# En développement, passez le cache à 'false' pour voir vos modifications HTML sans redémarrer le serveur
# ATTENTION : À passer à 'true' en production pour de meilleures performances
spring.thymeleaf.cache=false

# Encodage des pages HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.servlet.content-type=text/html

# Emplacement par défaut des fichiers HTML (déjà configuré ainsi par défaut)
spring.thymeleaf.prefix=classpath:/templates/

# spring.thymeleaf.prefix=/WEB-INF/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML

# =========================================================================
# 5. CONFIGURATION DU SERVEUR EMBARQUE (Tomcat)
# =========================================================================
# Port sur lequel l'application va s'exécuter (par défaut : 8080)
server.port=8080

# Encodage par défaut du serveur HTTP
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
